### PR TITLE
Various edits to error messages in makeDisplay() and cog()

### PR DESCRIPTION
**Pull request by lhsego**

### CODE REVIEW

**Comment by hafen** [comment]
Looks great!  Could you please do the following:

- add entries to NEWS.md about what you have done
- bump the version to 0.8.0.5 in both NEWS.md and DESCRIPTION
- update the date in DESCRIPTION
- add a dummy .R file with roxygen for trelliscope, with the version, date, and a link to http://tessera.io/docs-trelliscope/
- re-run roxygen and commit the updated .Rd files

I think that about covers it :)

**Comment by lhsego** [comment]
Will do.  Nice summary.

**Comment by hafen** [comment]
Also please shoot me a note when it is ready - once a PR is open, I don't get notified of updates.

**Comment by hafen** [comment]
BTW, the way I handle the NEWS.md is to keep adding entries to the topmost version section (currently the one that says 0.8.0.3) and keep updating the section header until a minor release bump (like when we get to 0.8.1) at which point I start a new section.  So just add to the existing section and bump the version in the header.

**Comment by lhsego** [comment]
Makes sense.  I'll keep that in mind about the PRs.  That explains a lot :)

**Pull request merged**
